version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - urjwan-network

  web-urjwan:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - urjwan-network
    user: root

  redis:
    image: redis:6-alpine
    networks:
      - urjwan-network


networks:
  urjwan-network:

volumes:
  postgres_data:
